# RSI settings
ip: 192.1.10.1
port: 49150
frequency: 50

# trajectory controller settings
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint]
ptp_vel: 0.1 # rad/sec
ptp_acc: 0.1 # rad/sec^2
max_error: 0.25 # rad
